# Generated by Django 3.2.7 on 2021-09-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20210921_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Eectronics'), ('2', 'Tea'), ('3', 'Fruits'), ('4', 'Vegetables'), ('5', 'Chicken'), ('6', 'Games')], default='1', max_length=50),
        ),
    ]
