# Generated by Django 3.2.7 on 2021-09-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Tea', 'Tea'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Chicken', 'Chicken'), ('Games', 'Games')], default='1', max_length=50),
        ),
    ]
