# Generated by Django 3.2.7 on 2021-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
