# Generated by Django 3.2.7 on 2021-09-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
